title: Albana Skeja # your name (or website title) here
logo: "/images/Alba Skeja.jpeg?raw=true" # your photo (or logo) here
description: > 
  Experienced financial and data science professional with expertise in business analytics, accounting, and predictive modeling. 
  As a CFO in Albania for 14 years, the company was involved in digital transformations, optimized financial systems, and enhanced operational efficiency. 
  In the U.S., I have spent the last three years specializing in accounts receivable and payable, using data-driven insights to improve financial processes. 
  Recently, I completed a Data Science course at TripleTen, gaining skills in machine learning, statistical analysis, and data visualization to drive data-driven business solutions.
  
  Data Science  
  <br><br>
  Ph.D Economic Science 
  <br><br>
  <a href="https://www.linkedin.com/in/albana-skeja-24as/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: 10350835511 # your Google Analytics tracking ID here         UA-000000-0
